---
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
env:
  node: true
  es6: true
parserOptions:
  ecmaVersion: 2021
rules:
  arrow-spacing:
    - warn
    - before: true
      after: true
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  comma-dangle:
    - error
    - always-multiline
  comma-spacing: error
  comma-style: error
  curly:
    - error
    - multi-line
    - consistent
  dot-location:
    - error
    - property
  handle-callback-err: "off"
  indent: "off"
  keyword-spacing: error
  max-nested-callbacks:
    - error
    - max: 4
  max-statements-per-line:
    - error
    - max: 2
  no-console: "off"
  no-empty-function: warn
  no-floating-decimal: error
  no-lonely-if: error
  no-multi-spaces: error
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
      maxBOF: 0
  no-shadow:
    - warns
    - allow:
        - err
        - resolve
        - reject
  no-trailing-spaces: "off"
  no-var: error
  no-unused-vars: warn
  no-empty: warn
  object-curly-spacing:
    - error
    - always
  prefer-const: warn
  quotes:
    - error
    - single
  semi:
    - error
    - never
  space-before-blocks: error
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: "off"
  yoda: error
