---
services:
  lilysbot:
    container_name: lilysbot
    # image:
    build: .
    depends_on: [redis-stack]
    restart: unless-stopped
    # develop:
    #   watch:
    #     - path: .
    #       action: rebuild

  redis-stack:
    image: redis/redis-stack:6.2.6-v9
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - PATH/TO/REDIS/data:/data
      - PATH/TO/REDIS/config/redis.conf:/redis.conf
    restart: unless-stopped
    environment:
      - TZ=Europe/London
