---
services:
  lilysbot:
    container_name: lilysbot
    # image:
    build: .
    depends_on: [redis-stack]
    develop:
      watch:
        - path: .
          action: rebuild
  redis-stack:
    image: redis/redis-stack:6.2.6-v9
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - /home/lily/app/redis/data:/data
      - /home/lily/app/redis/config/redis.conf:/redis.conf
    restart: always
    environment:
      - TZ=Europe/London
